import { AdminPanel, AdminPanelHead, AdminShell } from "../components/admin-shell";

export default function AdminOverview() {
  return (
    <AdminShell active="/admin" title="System overview" subtitle="What needs an operator decision today." actions={<button className="admin-button">Export daily report</button>}>
      <div className="admin-alert"><span>!</span><div><strong>Two adapters need attention</strong><p>Workday prepare success fell below 92%. Naukri selectors changed on one application flow.</p></div><a href="/admin/adapters">Open adapter health →</a></div>
      <div className="admin-metrics"><article><p>Active users · 7d</p><strong>1,284</strong><span className="trend up">↑ 12.4%</span><small>Sample metric</small></article><article><p>Free → Pro · 30d</p><strong>6.8%</strong><span className="trend up">↑ 0.9 pt</span><small>Sample target 7.5%</small></article><article className="critical-metric"><p>Free candidate-AI spend</p><strong>₹0.00</strong><span className="invariant">POLICY TARGET</span><small>Shared canonicalization tracked separately</small></article><article><p>Prepare success · 24h</p><strong>94.2%</strong><span className="trend down">↓ 1.8 pt</span><small>Sample adapter metric</small></article></div>
      <div className="admin-grid-main"><AdminPanel><AdminPanelHead eyebrow="Conversion funnel · 30 days" title="Activation to paid" action={<select><option>All acquisition</option><option>Organic</option><option>Referral</option></select>} /><div className="funnel-chart"><div><span><strong>4,820</strong>signed up</span><i style={{width:"100%"}} /></div><div><span><strong>3,761</strong>profile complete</span><i style={{width:"78%"}} /></div><div><span><strong>2,940</strong>first shortlist</span><i style={{width:"61%"}} /></div><div><span><strong>1,108</strong>application prepared</span><i style={{width:"23%"}} /></div><div className="paid"><span><strong>328</strong>upgraded</span><i style={{width:"7%"}} /></div></div><div className="admin-insight"><span>↗</span><p><strong>Largest recoverable drop: profile → first shortlist</strong>Users missing a compensation preference convert 18% less often.</p><button>Inspect cohort</button></div></AdminPanel>
        <AdminPanel><AdminPanelHead eyebrow="Live reliability" title="Adapter health" action={<a href="/admin/adapters">All adapters →</a>} /><div className="adapter-mini-list"><div><span className="health-light good" /><p><strong>Greenhouse</strong><small>99.1% prepare · 1,204 runs</small></p><b>Healthy</b></div><div><span className="health-light good" /><p><strong>LinkedIn</strong><small>96.8% assist · 842 runs</small></p><b>Healthy</b></div><div><span className="health-light warn" /><p><strong>Workday</strong><small>89.6% prepare · 418 runs</small></p><b className="warning">Degraded</b></div><div><span className="health-light bad" /><p><strong>Naukri</strong><small>72.4% one flow · 96 runs</small></p><b className="danger">Investigate</b></div></div></AdminPanel>
      </div>
      <div className="admin-grid-bottom"><AdminPanel><AdminPanelHead eyebrow="Human queue" title="Open incidents" action={<a href="/admin/incidents">View queue →</a>} /><div className="incident-table"><div><span className="severity sev2">SEV-2</span><p><strong>Naukri profile flow selector drift</strong><small>Opened 38m ago · 24 users affected</small></p><button>Assign</button></div><div><span className="severity sev3">SEV-3</span><p><strong>Workday resume attachment retries</strong><small>Opened 2h ago · 11 users affected</small></p><button>Open</button></div></div></AdminPanel><AdminPanel><AdminPanelHead eyebrow="Cost controls" title="AI spend by plan" action={<a href="/admin/ai-spend">Cost detail →</a>} /><div className="cost-split"><div className="cost-free"><span>FREE</span><strong>₹0.00</strong><small>0 accepted model calls</small></div><div><span>PRO · MTD</span><strong>₹18,462</strong><small>₹38.20 / active Pro user</small></div></div><div className="budget-line"><span>Monthly budget</span><strong>₹18,462 / ₹40,000</strong><i><b /></i></div></AdminPanel></div>
    </AdminShell>
  );
}
