import { AdminPanel, AdminPanelHead, AdminShell } from "../../components/admin-shell";

export default function AdminAiSpend() {
  return <AdminShell active="/admin/ai-spend" title="AI spend & policy" subtitle="Candidate AI and shared platform intelligence are budgeted separately." actions={<button className="admin-button" disabled>Edit budgets after API connection</button>}>
    <div className="invariant-hero"><div><span className="shield-zero">0</span><div><p>FREE CANDIDATE-AI GUARANTEE</p><h2>₹0.00 candidate AI spend</h2><span>Resume generation, answer drafting and semantic match calls stay blocked on Free.</span></div></div><b>SAMPLE POLICY VIEW</b></div>
    <div className="admin-alert"><span>i</span><div><strong>Platform intelligence is a separate lane</strong><p>Canonical field resolution may run centrally, is cached across form structure, and never shares candidate answers or bills the Free user.</p></div></div>
    <div className="admin-metrics compact"><article><p>Pro spend · MTD</p><strong>₹18,462</strong><small>46.2% of budget</small></article><article><p>Cost / active Pro</p><strong>₹38.20</strong><small>↓ ₹4.18 vs Jul</small></article><article><p>Gross margin · Pro</p><strong>84.7%</strong><small>At ₹249 monthly</small></article><article><p>Budget alerts</p><strong>0</strong><small>Next threshold 70%</small></article></div>
    <div className="admin-grid-main"><AdminPanel><AdminPanelHead eyebrow="August · daily spend" title="Model cost trend" action={<select><option>All Pro features</option><option>Resume tailoring</option><option>Screening drafts</option></select>} /><div className="bar-chart" aria-label="Daily AI spend bar chart">{[34,48,41,62,55,71,68,74,59,82,76,88,67,92,85,78,96,81,90,72,87,94,83,98,91,86].map((height,index) => <i key={index} style={{height:`${height}%`}}><span /></i>)}</div><div className="chart-axis"><span>1 Aug</span><span>13 Aug</span><span>26 Aug</span></div></AdminPanel><AdminPanel><AdminPanelHead eyebrow="Cost composition" title="By Pro feature" /><div className="feature-costs"><div><span><i className="cost-color one" /> Resume tailoring</span><strong>₹9,046 · 49%</strong></div><div><span><i className="cost-color two" /> Screening drafts</span><strong>₹5,723 · 31%</strong></div><div><span><i className="cost-color three" /> Match reasoning</span><strong>₹2,769 · 15%</strong></div><div><span><i className="cost-color four" /> Evidence checks</span><strong>₹924 · 5%</strong></div></div><div className="donut-placeholder"><div><strong>₹18.5k</strong><small>MTD</small></div></div></AdminPanel></div>
    <AdminPanel><AdminPanelHead eyebrow="Enforcement" title="Free candidate-generation gateway" action={<b className="policy-badge">FAIL CLOSED</b>} /><div className="policy-flow"><div><span>1</span><p><strong>Classify the operation</strong><small>USER_AI or PLATFORM_INTELLIGENCE</small></p></div><b>→</b><div><span>2</span><p><strong>Resolve entitlement</strong><small>Free USER_AI returns policy_denied</small></p></div><b>→</b><div><span>3</span><p><strong>Meter the correct lane</strong><small>Shared structure never carries answers</small></p></div><b>→</b><div><span>4</span><p><strong>Alert on invariant break</strong><small>Any billed Free USER_AI token is critical</small></p></div></div></AdminPanel>
  </AdminShell>;
}
