import { AdminPanel, AdminPanelHead, AdminShell } from "../../components/admin-shell";

export default function AdminIncidents() {
  return <AdminShell active="/admin/incidents" title="Incidents" subtitle="Current product impact, ownership and recovery state." actions={<button className="admin-button">Declare incident</button>}>
    <div className="incident-hero"><div><span className="health-light warn" /><div><p>CURRENT STATUS</p><h2>Degraded performance</h2><span>Candidate data safe · No autonomous submissions · Two portal workflows affected</span></div></div><small>Updated 6 minutes ago</small></div>
    <div className="incident-page-grid"><AdminPanel><AdminPanelHead eyebrow="Open · 2" title="Active incidents" /><article className="incident-card"><div className="incident-title"><span className="severity sev2">SEV-2</span><div><h3>Naukri profile flow selector drift</h3><p>INC-204 · Opened 38 minutes ago</p></div><b className="state-tag investigate">Investigating</b></div><dl><div><dt>Impact</dt><dd>24 Free users paused safely before autofill</dd></div><div><dt>Owner</dt><dd>A. Kumar · Adapter on-call</dd></div><div><dt>Mitigation</dt><dd>Flow paused; candidate support label downgraded</dd></div></dl><div className="incident-actions"><button>Open timeline</button><button>Update status</button></div></article><article className="incident-card"><div className="incident-title"><span className="severity sev3">SEV-3</span><div><h3>Workday resume attachment retries</h3><p>INC-203 · Opened 2 hours ago</p></div><b className="state-tag degraded">Monitoring</b></div><dl><div><dt>Impact</dt><dd>11 Pro users; no incorrect submissions</dd></div><div><dt>Owner</dt><dd>S. Iyer · Platform</dd></div><div><dt>Mitigation</dt><dd>Retry limit reduced; fallback upload surfaced</dd></div></dl><div className="incident-actions"><button>Open timeline</button><button>Resolve</button></div></article></AdminPanel>
      <aside><AdminPanel><AdminPanelHead eyebrow="Guardrails" title="Always-on checks" /><div className="guardrail-list"><div><span className="health-light good" /><p><strong>Free AI spend = ₹0</strong><small>Passing · checked 1m ago</small></p></div><div><span className="health-light good" /><p><strong>Auto-submit disabled</strong><small>Passing · all adapters</small></p></div><div><span className="health-light good" /><p><strong>Evidence policy</strong><small>Passing · 99.99%</small></p></div><div><span className="health-light good" /><p><strong>Audit event delivery</strong><small>Passing · 14s lag</small></p></div></div></AdminPanel><AdminPanel><AdminPanelHead eyebrow="Preparedness" title="Runbooks" /><div className="runbook-list"><a href="#">Portal selector drift <span>7 steps →</span></a><a href="#">Incorrect autofill report <span>9 steps →</span></a><a href="#">AI cost invariant break <span>SEV-1 →</span></a><a href="#">Provider outage <span>6 steps →</span></a></div></AdminPanel></aside></div>
  </AdminShell>;
}
