import type { ProductState } from "./product-types";

export const LOCAL_STORAGE_KEY = "job-hunter.local-workspace.v5";

export function initialProductState(): ProductState {
  return {
    version: 5,
    runtime: {
      mode: "local",
      connection: "CONNECTING",
      message: "Preparing your local workspace…",
    },
    profile: {
      name: "",
      email: "",
      phone: "",
      currentTitle: "",
      currentCompany: "",
      totalExperienceYears: null,
      targetRoles: [],
      preferredLocations: [],
      preferredWorkModes: [],
      employmentTypes: ["Full-time"],
      minimumSalary: null,
      skills: [],
      excludedSkills: [],
      dealBreakers: [],
      linkedinUrl: "",
      githubUrl: "",
      currentCTC: null,
      expectedCTC: null,
      noticePeriodDays: null,
      workAuthorization: "",
      searchProfileVersion: 1,
      primaryCoreStacks: [],
      acceptableCoreStacks: [],
      adjacentCareerTracks: [],
      desiredSeniorityLevels: [],
      preferredSkills: [],
      excludedCompanies: [],
      compensationConstraintMode: "SOFT",
      locationConstraintMode: "SOFT",
      workModeConstraintMode: "SOFT",
      employmentTypeConstraintMode: "SOFT",
      experienceTolerance: { smallGapYears: 1, maxPlausibleGapYears: 3, allowNearbySeniority: true },
      searchCountryCode: "IN",
      sponsorshipNeed: "UNKNOWN",
      relocationPreference: "UNKNOWN",
    },
    searchProfile: {
      schemaVersion: 1,
      profileVersion: 1,
      targetRoles: [],
      careerFamilies: [],
      primaryCoreStacks: [],
      acceptableCoreStacks: [],
      adjacentCareerTracks: [],
      desiredSeniorityLevels: [],
      preferredSkills: [],
      excludedSkills: [],
      preferredLocations: [],
      preferredWorkModes: [],
      employmentTypes: ["FULL_TIME"],
      minimumSalary: null,
      compensationConstraintMode: "SOFT",
      locationConstraintMode: "SOFT",
      workModeConstraintMode: "SOFT",
      employmentTypeConstraintMode: "SOFT",
      experienceTolerance: { smallGapYears: 1, maxPlausibleGapYears: 3, allowNearbySeniority: true },
      excludedCompanies: [],
      dealBreakers: [],
      countryCode: "IN",
      workAuthorization: "UNKNOWN",
      sponsorshipNeed: "UNKNOWN",
      relocationPreference: "UNKNOWN",
    },
    onboarding: {
      status: "NOT_STARTED",
      lastStep: "intent",
      complete: false,
      intentReviewed: false,
      resumeReviewed: false,
      searchReviewed: false,
      valueShown: false,
      resumeSkipped: false,
      searchReadiness: 0,
    },
    resume: null,
    jobs: [
      {
        id: "local-razorpay-platform",
        company: "Razorpay",
        logo: "R",
        role: "Platform Engineer",
        location: "Bengaluru · Hybrid",
        salary: "₹32–48 LPA",
        matchScore: 94,
        fit: "STRONG_FIT",
        fitReasons: ["Backend and infrastructure ownership align", "Kubernetes and AWS are in your target stack", "Location matches your search"],
        gaps: ["Payments domain experience is preferred"],
        unknowns: [],
        skills: ["Node.js", "Kubernetes", "AWS"],
        source: "Greenhouse",
        support: { mode: "AUTOFILL", label: "Smart Fill", reason: "Copilot can fill verified fields; you review and submit." },
        fresh: "6h",
        url: "https://razorpay.com/jobs",
        status: "MATCHED",
        actionability: { status: "OPEN", canApply: true, discoveryEligible: true, reason: null },
        applicationSchema: { available: true, freshness: "FRESH", observedAt: new Date().toISOString(), fieldCount: 31, requiredFieldCount: 18 },
        availability: { status: "ACTIVE", reason: "SAMPLE_LISTING", confidence: 1, explicitDeadline: null, lastVerifiedAt: new Date().toISOString(), closedAt: null, verificationRecommended: false },
        whyThisJob: { scoringMethod: "HEURISTIC", evidenceCoverage: 0.92, hardRequirementsFirst: true },
      },
      {
        id: "local-atlassian-backend",
        company: "Atlassian",
        logo: "A",
        role: "Senior Backend Engineer",
        location: "Bengaluru · Remote",
        salary: "₹38–55 LPA",
        matchScore: 89,
        fit: "STRONG_FIT",
        fitReasons: ["Seniority matches your experience range", "Distributed-systems scope is relevant", "Remote India matches your preference"],
        gaps: ["Java depth needs confirmation"],
        unknowns: ["Employer sponsorship policy is not stated"],
        skills: ["Java", "Distributed systems", "AWS"],
        source: "Workday",
        support: { mode: "AUTOFILL", label: "Smart Fill", reason: "Copilot can inspect the employer form after you open it." },
        fresh: "10h",
        url: "https://www.atlassian.com/company/careers",
        status: "MATCHED",
        actionability: { status: "OPEN", canApply: true, discoveryEligible: true, reason: null },
        applicationSchema: { available: true, freshness: "FRESH", observedAt: new Date().toISOString(), fieldCount: 42, requiredFieldCount: 23 },
        availability: { status: "ACTIVE", reason: "SAMPLE_LISTING", confidence: 1, explicitDeadline: null, lastVerifiedAt: new Date().toISOString(), closedAt: null, verificationRecommended: false },
        whyThisJob: { scoringMethod: "HEURISTIC", evidenceCoverage: 0.87, hardRequirementsFirst: true },
      },
      {
        id: "local-postman-cloud",
        company: "Postman",
        logo: "P",
        role: "Software Engineer, Cloud",
        location: "Remote · India",
        salary: "₹28–42 LPA",
        matchScore: 81,
        fit: "POSSIBLE_FIT",
        fitReasons: ["TypeScript and Node.js overlap", "Remote India matches your search", "Cloud platform scope is adjacent"],
        gaps: ["GCP evidence is limited", "Role level needs review"],
        unknowns: ["Compensation details may change by level"],
        skills: ["TypeScript", "Node.js", "GCP"],
        source: "Greenhouse",
        support: { mode: "AUTOFILL", label: "Smart Fill", reason: "Verified non-sensitive fields can be filled." },
        fresh: "1d",
        url: "https://www.postman.com/company/careers",
        status: "CLOSE",
        actionability: { status: "OPEN", canApply: true, discoveryEligible: true, reason: null },
        applicationSchema: { available: true, freshness: "RECENT", observedAt: new Date(Date.now() - 4 * 86400000).toISOString(), fieldCount: 27, requiredFieldCount: 15 },
        availability: { status: "ACTIVE", reason: "SAMPLE_LISTING", confidence: 1, explicitDeadline: null, lastVerifiedAt: new Date().toISOString(), closedAt: null, verificationRecommended: false },
        whyThisJob: { scoringMethod: "HEURISTIC", evidenceCoverage: 0.79, hardRequirementsFirst: true },
      },
    ],
    savedJobs: [],
    jobFeed: {
      status: "READY",
      stale: false,
      staleReasons: [],
      generationId: "browser-local-sample",
      builtAt: new Date().toISOString(),
      durationMs: 0,
      total: 3,
      nextCursor: null,
      hasMore: false,
    },
    applications: [],
    attention: { blockers: [], gaps: [] },
    readiness: {
      credible: false,
      label: "Profile foundation not ready",
      percent: null,
      knownFieldCount: 0,
      requiredFieldCount: null,
      missing: [],
    },
    plan: { id: "FREE", trialStatus: "AVAILABLE", trialDays: 7 },
  };
}
