import assert from "node:assert/strict";
import test from "node:test";
import {readFile,readdir} from "node:fs/promises";
import {PGlite} from "@electric-sql/pglite";
import {Kysely,PGliteDialect} from "kysely";
import {CandidateTruthService,HmacCandidateValueFingerprinter} from "@job-hunter-v2/candidate-truth";
import {AesGcmCandidatePayloadCipher} from "@job-hunter-v2/onboarding";
import {VerifiedLearningService} from "@job-hunter-v2/verified-learning";
import {LearningInboxCaptureSchema,ConfirmLearningNoteSchema} from "@job-hunter-v2/contracts";
import {KyselyCandidateTruthRepository,KyselyVerifiedLearningRepository,KyselyLearningRecovery,learningFingerprintKeyStatus,type V2Database} from "./index.js";

test("note rotation preserves exact historical replay, atomic confirmation and immutable tombstones",async()=>{
  const pg=new PGlite(),db=new Kysely<V2Database>({dialect:new PGliteDialect({pglite:pg})});
  try{
    const dir=new URL("../../../database/migrations/",import.meta.url);
    for(const file of(await readdir(dir)).filter(f=>/^\d{4}_.*\.sql$/.test(f)&&!f.startsWith("0033")).sort())await pg.exec(await readFile(new URL(file,dir),"utf8"));
    const owner={accountId:crypto.randomUUID(),candidateId:crypto.randomUUID()};
    await pg.query("INSERT INTO accounts(id,account_type,contributes_to_global_learning) VALUES($1,'TEST',false)",[owner.accountId]);
    const oldSecret="rotation-fixture-old-secret-at-least-32",newSecret="rotation-fixture-new-secret-at-least-32";
    const old=new HmacCandidateValueFingerprinter(oldSecret,1),rotated=new HmacCandidateValueFingerprinter(newSecret,2,[{keyVersion:1,secret:oldSecret}]),cipher=new AesGcmCandidatePayloadCipher(new Uint8Array(32).fill(3),1);
    const truth=new CandidateTruthService(new KyselyCandidateTruthRepository(db),old);await truth.ensureCandidate(owner);
    const run=await new VerifiedLearningService(new KyselyVerifiedLearningRepository(db),old,cipher).startRun({...owner,idempotencyKey:"rotation-test",request:{schemaVersion:1,requestId:crypto.randomUUID(),jobId:null,targetUrl:"https://synthetic.example.test/rotation/apply",extensionVersion:"0.1.0",protocolVersion:1}});
    const request=()=>({schemaVersion:1 as const,itemId:crypto.randomUUID(),applicationId:run.applicationId,applicationRunId:run.applicationRunId,question:"Synthetic name",answer:"Synthetic",source:"EXPLICIT_SAVE" as const});
    const input={canonicalKey:"FIRST_NAME" as const,answer:"Synthetic",expectedCurrentVersionId:null,confirmedGlobalDefault:true};
    const privateString=(value:unknown)=>({schemaVersion:1 as const,dataClass:"CANDIDATE_PRIVATE" as const,kind:"STRING" as const,value:JSON.stringify(value)});
    const legacy=LearningInboxCaptureSchema.parse(request()),payload=cipher.encrypt(privateString({question:legacy.question,answer:legacy.answer,source:legacy.source}));
    await pg.query("INSERT INTO candidate_learning_inbox(id,account_id,candidate_id,application_id,run_id,payload,fingerprint,expires_at) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,now()+interval '30 days')",[legacy.itemId,owner.accountId,owner.candidateId,run.applicationId,run.applicationRunId,JSON.stringify({keyVersion:payload.keyVersion,initializationVector:Buffer.from(payload.initializationVector).toString("base64"),authenticationTag:Buffer.from(payload.authenticationTag).toString("base64"),ciphertext:Buffer.from(payload.ciphertext).toString("base64")}),old.fingerprint(privateString(legacy)).digest]);
    const saved=await truth.saveGroup({...owner,commitPoint:"EXPLICIT_SAVE",applicationId:null,idempotencyKey:`note-confirm:${legacy.itemId}`,items:[{itemKey:legacy.itemId,canonicalKey:input.canonicalKey,normalizedValue:{schemaVersion:1,dataClass:"CANDIDATE_PRIVATE",kind:"STRING",value:input.answer},scopeType:"GLOBAL",entityId:null,source:"PROFILE",expectedCurrentVersionId:null}]});
    await pg.query("INSERT INTO candidate_learning_note_confirmations(item_id,candidate_id,request_fingerprint,change_set_id,canonical_key) VALUES($1,$2,$3,$4,'FIRST_NAME')",[legacy.itemId,owner.candidateId,old.fingerprint(privateString(ConfirmLearningNoteSchema.parse(input))).digest,saved.changeSetId]);
    await pg.exec(await readFile(new URL("0033_learning_fingerprint_versions.sql",dir),"utf8"));
    const before=new KyselyLearningRecovery(db,cipher,old),after=new KyselyLearningRecovery(db,cipher,rotated),missing=new KyselyLearningRecovery(db,cipher,new HmacCandidateValueFingerprinter(newSecret,2));
    assert.equal((await after.capture(owner,legacy)).idempotentReplay,true);
    assert.equal((await after.confirm(owner,legacy.itemId,input)).changeSetId,saved.changeSetId);
    assert.equal((await pg.query<{fingerprint_key_version:number|null}>("SELECT fingerprint_key_version FROM candidate_learning_inbox WHERE id=$1",[legacy.itemId])).rows[0]?.fingerprint_key_version,null);
    const pending=request();await before.capture(owner,pending);
    assert.equal((await after.capture(owner,pending)).idempotentReplay,true);
    await assert.rejects(after.capture(owner,{...pending,answer:"different"}),/cannot be verified/);
    await assert.rejects(missing.capture(owner,pending),/cannot be verified/);
    await assert.rejects(after.capture({...owner,candidateId:crypto.randomUUID()},pending),/not found/);
    const confirm={...input,canonicalKey:"LAST_NAME" as const};
    const confirmed=await after.confirm(owner,pending.itemId,confirm);
    assert.equal((await pg.query<{fingerprint_key_version:number}>("SELECT fingerprint_key_version FROM candidate_learning_note_confirmations WHERE item_id=$1",[pending.itemId])).rows[0]?.fingerprint_key_version,2);
    await after.remove(owner,pending.itemId);
    assert.equal((await after.capture(owner,pending)).status,"DELETED");
    assert.equal((await after.confirm(owner,pending.itemId,confirm)).changeSetId,confirmed.changeSetId);
    await assert.rejects(after.confirm(owner,pending.itemId,{...confirm,answer:"changed"}),/cannot be verified/);
    await assert.rejects(missing.confirm(owner,legacy.itemId,input),/cannot be verified/);
    for(const statement of ["UPDATE candidate_learning_inbox SET fingerprint=repeat('a',64)","UPDATE candidate_learning_inbox SET expires_at=expires_at+interval '1 day'","UPDATE candidate_learning_inbox SET payload='{}'::jsonb","UPDATE candidate_learning_inbox SET status='PENDING' WHERE status='DELETED'","DELETE FROM candidate_learning_inbox","UPDATE candidate_learning_note_confirmations SET canonical_key='EMAIL'","DELETE FROM candidate_learning_note_confirmations"])await assert.rejects(pg.exec(statement),/immutable|tombstone|append-only/);
    const expired=request();await after.capture(owner,expired);await pg.query("UPDATE candidate_learning_inbox SET expires_at=clock_timestamp()-interval '1 second' WHERE id=$1",[expired.itemId]);
    assert.equal((await after.capture(owner,expired)).status,"EXPIRED");await assert.rejects(after.confirm(owner,expired.itemId,{...input,canonicalKey:"CURRENT_LOCATION"}),/expired/);
    const atomic=request();await after.capture(owner,atomic);
    await pg.exec("CREATE FUNCTION fail_note_receipt() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic receipt outage'; END $$; CREATE TRIGGER fail_note_receipt BEFORE INSERT ON candidate_learning_note_confirmations FOR EACH ROW EXECUTE FUNCTION fail_note_receipt()");
    const count=async()=>Number((await pg.query<{count:string}>("SELECT count(*) AS count FROM candidate_answer_versions")).rows[0]!.count);
    const prior=await count();await assert.rejects(after.confirm(owner,atomic.itemId,{...input,canonicalKey:"CURRENT_LOCATION"}),/synthetic receipt outage/);assert.equal(await count(),prior);
    await pg.exec("DROP TRIGGER fail_note_receipt ON candidate_learning_note_confirmations");
    await after.confirm(owner,atomic.itemId,{...input,canonicalKey:"CURRENT_LOCATION"});assert.equal(await count(),prior+1);
    const inventory=await learningFingerprintKeyStatus(db,2,[1]);
    assert.equal(inventory.status,"LEGACY_REVIEW_REQUIRED");assert.equal(JSON.stringify(inventory).includes("Synthetic"),false);
    assert.equal((await learningFingerprintKeyStatus(db,2)).status,"MISSING_HISTORICAL_KEYS");
    assert.ok(inventory.groups.some(g=>g.source==="NOTE_RECEIPT"&&g.key_version===2&&g.availability==="CONFIGURED"));
    await assert.rejects(learningFingerprintKeyStatus(db,2,[2]),/Invalid/);
    const malformed=new KyselyLearningRecovery(db,{encrypt:value=>cipher.encrypt(value),decrypt:()=>({schemaVersion:1,dataClass:"CANDIDATE_PRIVATE",kind:"STRING",value:"secret-parser-excerpt {"})},rotated);
    await assert.rejects(malformed.list(owner),error=>{assert.equal(String(error),"Error: Private note cannot be read.");return true;});
  }finally{await db.destroy();}
});
