import { AdminPanel, AdminPanelHead, AdminShell } from "../../components/admin-shell";

export default function AdminBilling() {
  return <AdminShell active="/admin/billing" title="Billing" subtitle="Revenue, renewals and payment exceptions for Indian customers." actions={<button className="admin-button">Open payment provider</button>}>
    <div className="admin-metrics compact"><article><p>MRR</p><strong>₹1.24L</strong><small>↑ 14.8% vs Jul</small></article><article><p>Paying users</p><strong>482</strong><small>446 monthly · 36 weekly</small></article><article><p>Renewal rate</p><strong>91.2%</strong><small>30-day rolling</small></article><article><p>Payment recovery</p><strong>68.4%</strong><small>26 of 38 recovered</small></article></div>
    <div className="admin-grid-main"><AdminPanel><AdminPanelHead eyebrow="Plan mix" title="Active subscriptions" /><div className="billing-plan-list"><div><span>Monthly launch · ₹249</span><strong>446</strong><i><b style={{width:'92.5%'}} /></i></div><div><span>Weekly launch · ₹79</span><strong>36</strong><i><b style={{width:'7.5%'}} /></i></div></div><div className="admin-insight"><span>₹</span><p><strong>Protect launch-price trust</strong>Show the regular price only while the introductory discount is real and time-bounded.</p></div></AdminPanel><AdminPanel><AdminPanelHead eyebrow="Payment methods" title="Successful payments" /><div className="payment-methods"><div><span>UPI</span><strong>58%</strong></div><div><span>Cards</span><strong>31%</strong></div><div><span>Netbanking</span><strong>8%</strong></div><div><span>Other</span><strong>3%</strong></div></div><p className="operator-note">Keep UPI prominent at checkout; it is the clearest default for this customer base.</p></AdminPanel></div>
    <AdminPanel><AdminPanelHead eyebrow="Requires action" title="Payment exceptions" action={<a href="#">Export reconciliation →</a>} /><div className="admin-data-table payment-table"><div className="admin-data-row table-head"><span>User</span><span>Plan</span><span>Amount</span><span>State</span><span>Next retry</span><span>Action</span></div>{[['Meera Shah','Monthly','₹249','Retrying','27 Aug, 10:00','Open'],['Rohan Kapoor','Monthly','₹249','Grace period','28 Aug, 14:20','Notify'],['Diya Menon','Weekly','₹79','Refund review','—','Review']].map(row => <div className="admin-data-row" key={row[0]}>{row.map((cell,index) => <span key={cell}>{index === 3 ? <b className="state-tag degraded">{cell}</b> : index === 5 ? <button>{cell}</button> : cell}</span>)}</div>)}</div></AdminPanel>
  </AdminShell>;
}
