"use client";

import { AppShell, Badge, Panel, PanelHead } from "../../components/app-shell";
import { useProduct } from "../../components/product-provider";

export default function DocumentsPage() {
  const { state, busy, uploadResume } = useProduct();
  const resume = state.resume;
  // A tracked application is not evidence that a document was generated.
  // Keep this empty until the document API returns actual version records.
  const tailoredCount = 0;
  return (
    <AppShell active="/app/documents" eyebrow="Documents" title="One verified source for every application." subtitle="Resume extraction proposes facts; only your confirmation promotes them." actions={<label className="button button-dark file-button">{busy || (resume ? "Upload new version" : "Upload resume")}<input type="file" accept="application/pdf,.pdf" onChange={(event) => event.target.files?.[0] && void uploadResume(event.target.files[0])} /></label>}>
      {resume ? <div className="document-hero"><div className="large-doc"><span /><span /><span /><span /></div><div><p className="page-eyebrow">MASTER RESUME · {resume.status}</p><h2>{resume.fileName}</h2><p>{new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(resume.uploadedAt))}{resume.pageCount ? ` · ${resume.pageCount} pages` : ""} · PDF</p><div><Badge tone={resume.status === "CONFIRMED" ? "good" : "warn"}>{resume.status === "CONFIRMED" ? "Candidate verified" : "Review required"}</Badge>{resume.parseConfidence != null ? <Badge>{Math.round(resume.parseConfidence * 100)}% parse confidence</Badge> : <Badge>Local metadata only</Badge>}<Badge>{state.profile.skills.length} skills</Badge></div>{resume.warning ? <p className="document-warning">{resume.warning}</p> : null}</div><div className="document-actions"><a className="button button-light" href="/app/onboarding">Review facts</a></div></div> : <Panel><div className="empty-state document-empty"><span>⇧</span><strong>Add your master resume.</strong><p>Use a PDF up to 10 MB. The local backend extracts text and proposes a profile without silently overwriting your confirmed facts.</p><label className="button button-dark file-button">Choose PDF<input type="file" accept="application/pdf,.pdf" onChange={(event) => event.target.files?.[0] && void uploadResume(event.target.files[0])} /></label></div></Panel>}
      <div className="app-grid-two even"><Panel><PanelHead eyebrow="Included in Free" title="Verified resume foundation" /><div className="tool-list"><article><span>✓</span><div><strong>Parser review</strong><p>Inspect identity, dates, experience and skills before they become trusted.</p></div><a href="/app/onboarding">Review</a></article><article><span>✓</span><div><strong>Fact inventory</strong><p>See which fields have candidate-approved evidence and which remain unknown.</p></div><a href="/app/profile">Open facts</a></article><article><span>✓</span><div><strong>Master resume</strong><p>Keep one source document without generating unverified experience.</p></div><Badge tone={resume ? "good" : "warn"}>{resume ? "Ready" : "Missing"}</Badge></article></div></Panel><Panel className="locked-panel"><div className="pro-lock">PRO</div><PanelHead eyebrow="AI-assisted" title="Tailor without inventing" /><p>Pro can reprioritise verified bullets and terminology for a specific role. It cannot add unsupported skills, numbers or employers.</p><div className="locked-preview"><div><span>Match role language</span><Badge tone="pro">Pro</Badge></div><div><span>Rewrite summary</span><Badge tone="pro">Pro</Badge></div><div><span>Evidence gap check</span><Badge tone="pro">Pro</Badge></div></div><a href="/app/profile#plan" className="button button-primary">See the 7-day pass</a></Panel></div>
      <Panel><PanelHead eyebrow="Versions" title="Application documents" /><div className="versions-grid">{resume ? <article><div className="mini-document"><span /><span /><span /></div><div><strong>{resume.fileName}</strong><p>Master · {resume.status.toLowerCase()}</p></div><Badge tone={resume.status === "CONFIRMED" ? "good" : "warn"}>{resume.status === "CONFIRMED" ? "Current" : "Review"}</Badge></article> : null}{tailoredCount ? <article><div className="mini-document"><span /><span /><span /></div><div><strong>{tailoredCount} application document{tailoredCount === 1 ? "" : "s"}</strong><p>Generated for tracked roles</p></div><Badge tone="pro">Pro</Badge></article> : <article className="disabled"><div className="mini-document"><span /><span /><span /></div><div><strong>No tailored versions yet</strong><p>Created only after you choose a role</p></div><Badge>Empty</Badge></article>}</div></Panel>
    </AppShell>
  );
}
