"use client";

import { AppShell, Badge, Panel, PanelHead } from "../components/app-shell";
import { useProduct } from "../components/product-provider";

function fitCopy(fit: string) {
  return fit === "STRONG_FIT" ? "Strong fit" : fit === "POSSIBLE_FIT" ? "Possible fit" : "Review carefully";
}

export default function CandidateHome() {
  const { state, hydrated } = useProduct();
  const jobs = state.jobs.filter((job) => !job.dismissed);
  const attentionCount = state.attention.blockers.length + state.attention.gaps.length;
  const firstName = state.profile.name.split(/\s+/).filter(Boolean)[0] || "there";
  const date = new Intl.DateTimeFormat("en-IN", { weekday: "long", day: "numeric", month: "long" }).format(new Date());

  return (
    <AppShell active="/app" eyebrow={date} title={`Good morning, ${firstName}.`} subtitle={state.onboarding.complete ? (jobs.length ? `${jobs.filter((job) => job.fit === "STRONG_FIT").length} strong roles are worth reviewing.` : "Your search is ready for the next discovery run.") : "Finish your search foundation before Copilot recommends roles."} actions={<a href={state.onboarding.complete ? "/app/jobs" : "/app/onboarding"} className="button button-dark">{state.onboarding.complete ? "Browse all jobs" : "Continue setup"}</a>}>
      {!hydrated ? <div className="loading-state"><i /><span>Loading your local workspace…</span></div> : null}
      {state.runtime.mode === "local" ? <div className="mode-banner sample-mode"><span className="mode-icon">◎</span><div><strong>Browser-local UI preview</strong><p>Jobs and scores on this hosted test are sample data. Your onboarding and changes stay in this browser; run the local API for discovered jobs and PDF parsing.</p></div><a href="/app/profile#privacy" className="button button-dark">View data mode</a></div> : <div className="mode-banner"><span className="mode-icon">✦</span><div><strong>Your Pro pass waits for your first Pro action</strong><p>Setup does not consume trial days. Start it when you tailor a resume, cover letter or grounded screening draft.</p></div><a href="/app/profile#plan" className="button button-dark">See Pro features</a></div>}

      <div className="metric-grid"><article><span>Current matches</span><strong>{jobs.length}</strong><small>{jobs.filter((job) => job.fit === "STRONG_FIT").length} strong fit</small></article><article><span>Ready to review</span><strong>{jobs.filter((job) => job.fit === "STRONG_FIT").length}</strong><small>Hard requirements first</small></article><article><span>Applications</span><strong>{state.applications.length}</strong><small>{state.applications.filter((item) => item.stage === "Submitted").length} submitted</small></article><article className="attention-metric"><span>Needs you</span><strong>{attentionCount}</strong><small>{state.attention.blockers.length ? "Active form blockers first" : "Reusable preparation gaps"}</small></article></div>

      <div className="app-grid-two">
        <Panel><PanelHead eyebrow="Today’s shortlist" title="Best current matches" action={<a className="inline-link" href="/app/jobs">View all {jobs.length || ""} →</a>} />{jobs.length ? <div className="compact-job-list">{jobs.slice(0, 3).map((job) => <article key={job.id}><span className="company-avatar">{job.logo}</span><div><p>{job.company} · {job.source}</p><h3>{job.role}</h3><small>{job.location} · {job.salary}</small><div className="skill-row">{job.skills.slice(0, 2).map((skill) => <span key={skill}>{skill}</span>)}</div></div><div className="job-side"><strong className={`fit-text ${job.fit.toLowerCase()}`}>{fitCopy(job.fit)}</strong>{job.matchScore != null ? <small>{job.matchScore}% match</small> : null}<a href={`/app/jobs#${job.id}`}>Review</a></div></article>)}</div> : <div className="empty-state"><span>⌕</span><strong>No matches yet</strong><p>Finish onboarding or run job discovery from your local backend.</p><a href="/app/onboarding" className="button button-light">Check search setup</a></div>}</Panel>
        <div className="stacked-panels">
          <Panel className="attention-panel"><PanelHead eyebrow="Attention" title="Only the decisions that need you" action={<Badge tone={attentionCount ? "warn" : "good"}>{attentionCount ? `${attentionCount} open` : "Clear"}</Badge>} />{state.attention.blockers[0] ? <div className="attention-item"><span>!</span><div><strong>{state.attention.blockers[0].company} · active application</strong><p>{state.attention.blockers[0].reason}</p><a href="/app/attention">Continue application →</a></div></div> : state.attention.gaps[0] ? <div className="attention-item predictive"><span>↗</span><div><strong>{state.attention.gaps[0].label}</strong><p>Likely needed by {state.attention.gaps[0].affectedJobCount} recent applications. Answer once when convenient.</p><a href="/app/attention">Improve readiness →</a></div></div> : <div className="mini-empty"><span>✓</span><p><strong>Nothing needs you right now.</strong><small>Copilot paused nowhere and found no recent preparation gaps.</small></p></div>}</Panel>
          <Panel><PanelHead eyebrow="Readiness" title={state.readiness.credible ? "Application readiness" : "Profile foundation"} action={state.readiness.percent != null ? <strong className="readiness-score">{state.readiness.percent}%</strong> : <Badge tone="good">FOUNDATION</Badge>} /><div className="readiness-copy"><p>{state.readiness.label}</p><small>{state.readiness.credible ? "Based only on repeatable fields in fresh application schemas." : "A percentage appears only after enough recent application-field evidence exists."}</small></div><div className="check-list"><div className={state.resume?.status === "CONFIRMED" || state.resume?.status === "SKIPPED" ? "done" : ""}><span>{state.resume?.status === "CONFIRMED" || state.resume?.status === "SKIPPED" ? "✓" : "1"}</span><p><strong>Career evidence</strong><small>{state.resume?.status === "CONFIRMED" ? "Resume facts verified" : state.resume?.status === "SKIPPED" ? "Manual profile verified" : "Needs review"}</small></p></div><div className={state.onboarding.searchReviewed ? "done" : ""}><span>{state.onboarding.searchReviewed ? "✓" : "2"}</span><p><strong>Search preferences</strong><small>{state.onboarding.searchReviewed ? "Essential filters saved" : "Choose locations and work mode"}</small></p></div><div><span>3</span><p><strong>Connect browser Copilot</strong><small>Optional until you apply</small></p><a href="/app/profile#connections">Connect</a></div></div></Panel>
        </div>
      </div>

      <Panel className="activity-panel"><PanelHead eyebrow="Pipeline" title="Recent application activity" action={<a href="/app/applications" className="inline-link">Open tracker →</a>} />{state.applications.length ? <div className="activity-timeline">{state.applications.slice(0, 3).map((application) => <div key={application.id}><span className={`activity-dot ${application.stage === "Submitted" ? "good" : application.stage === "Needs you" ? "warn" : ""}`} /><p><strong>{application.company} · {application.role}</strong><small>{application.nextAction}</small></p><Badge tone={application.stage === "Submitted" ? "good" : application.stage === "Needs you" ? "warn" : "neutral"}>{application.stage}</Badge></div>)}</div> : <div className="empty-state horizontal-empty"><span>↗</span><div><strong>Your tracker starts with the first application.</strong><p>Review a strong-fit job, prepare it with Copilot, then keep every outcome in one place.</p></div><a href="/app/jobs" className="button button-light">Review jobs</a></div>}</Panel>
    </AppShell>
  );
}
