-- Policy v3: ordinary verified facts have global defaults and explicit overrides.
-- Historical answer values/scopes are retained; no candidate data is rewritten.
INSERT INTO canonical_fields (canonical_key,description,value_type,entity_type,status) VALUES
('LEGAL_FIRST_NAME','Candidate-verified legal given name.','STRING',NULL,'ACTIVE'),
('LEGAL_MIDDLE_NAME','Candidate-verified legal middle name.','STRING',NULL,'ACTIVE'),
('LEGAL_LAST_NAME','Candidate-verified legal family name.','STRING',NULL,'ACTIVE'),
('PREFERRED_FIRST_NAME','Preferred given name.','STRING',NULL,'ACTIVE'),
('PREFERRED_LAST_NAME','Preferred family name.','STRING',NULL,'ACTIVE'),
('FIRST_NAME','Standard given name used for applications.','STRING',NULL,'ACTIVE'),
('LAST_NAME','Standard family name used for applications.','STRING',NULL,'ACTIVE'),
('FULL_NAME','Complete candidate name.','STRING',NULL,'ACTIVE'),
('EMAIL','Application contact email.','STRING',NULL,'ACTIVE'),
('PHONE','Application contact phone number.','PHONE',NULL,'ACTIVE'),
('CURRENT_ADDRESS','Candidate''s current postal address.','ADDRESS',NULL,'ACTIVE'),
('CURRENT_LOCATION','Candidate''s current city or locality.','STRING',NULL,'ACTIVE'),
('LINKEDIN_URL','Candidate''s LinkedIn profile.','URL',NULL,'ACTIVE'),
('GITHUB_URL','Candidate''s GitHub profile.','URL',NULL,'ACTIVE'),
('PORTFOLIO_URL','Candidate''s portfolio or professional website.','URL',NULL,'ACTIVE'),
('CURRENT_COMPANY','Candidate''s current or most recent employer.','STRING',NULL,'ACTIVE'),
('CURRENT_JOB_TITLE','Candidate''s current or most recent job title.','STRING',NULL,'ACTIVE'),
('CURRENT_CTC','Candidate''s current compensation.','MONEY',NULL,'ACTIVE'),
('NOTICE_PERIOD','Candidate''s current notice period in days.','INTEGER',NULL,'ACTIVE'),
('TOTAL_EXPERIENCE','Candidate''s total professional experience.','DURATION',NULL,'ACTIVE'),
('SKILLS','Candidate-verified professional skills.','MULTI_ENUM',NULL,'ACTIVE'),
('PERSONAL_SUMMARY','Candidate-verified professional summary.','RICH_TEXT',NULL,'ACTIVE'),
('RESUME','Candidate-selected master or application resume.','FILE_REF',NULL,'ACTIVE'),
('WORK_AUTHORIZATION','Whether the candidate may work in a specific country.','BOOLEAN',NULL,'ACTIVE'),
('SPONSORSHIP_REQUIRED','Whether the candidate requires sponsorship in a specific country.','BOOLEAN',NULL,'ACTIVE'),
('AGE_OVER_18','Whether the candidate is at least 18 years old.','BOOLEAN',NULL,'ACTIVE'),
('GOVERNMENT_EMPLOYEE','Whether the candidate is currently a government employee.','BOOLEAN',NULL,'ACTIVE'),
('NON_COMPETE','Whether the candidate is subject to a non-compete obligation.','BOOLEAN',NULL,'ACTIVE'),
('PREVIOUSLY_EMPLOYED_BY_COMPANY','Whether the candidate previously worked for the hiring company.','BOOLEAN',NULL,'ACTIVE'),
('RELATIVE_AT_COMPANY','Whether the candidate has a relative at the hiring company.','BOOLEAN',NULL,'ACTIVE'),
('EXPECTED_CTC','Candidate''s expected compensation for a context.','MONEY',NULL,'ACTIVE'),
('RELOCATION','Candidate''s relocation preference for a context.','BOOLEAN',NULL,'ACTIVE'),
('PREFERRED_LOCATIONS','Candidate''s preferred work locations.','MULTI_ENUM',NULL,'ACTIVE'),
('START_DATE','Candidate''s available start date for one application.','DATE',NULL,'ACTIVE'),
('WORK_MODE_REQUIREMENT','Candidate response to a job-specific work-mode requirement.','BOOLEAN',NULL,'ACTIVE'),
('LAST_WORKING_DAY','Confirmed last working day at the previous employer.','DATE',NULL,'ACTIVE'),
('AI_CODING_EXPERIENCE','Candidate-confirmed hands-on experience with AI coding assistants.','BOOLEAN',NULL,'ACTIVE'),
('HEARING_SOURCE','How the candidate learned about one role.','ENUM',NULL,'ACTIVE'),
('COVER_LETTER','Job-grounded cover letter draft.','RICH_TEXT',NULL,'ACTIVE'),
('EMPLOYMENT_COMPANY','Employer for one stable employment entity.','STRING','EMPLOYMENT','ACTIVE'),
('EMPLOYMENT_TITLE','Job title for one stable employment entity.','STRING','EMPLOYMENT','ACTIVE'),
('EMPLOYMENT_DATE_RANGE','Dates for one stable employment entity.','DATE_RANGE','EMPLOYMENT','ACTIVE'),
('EMPLOYMENT_LOCATION','Location for one stable employment entity.','STRING','EMPLOYMENT','ACTIVE'),
('EMPLOYMENT_DESCRIPTION','Resume-supported description for one employment entity.','RICH_TEXT','EMPLOYMENT','ACTIVE'),
('EMPLOYMENT_SKILLS','Resume-supported technologies for one employment entity.','MULTI_ENUM','EMPLOYMENT','ACTIVE'),
('EDUCATION_INSTITUTION','Institution for one stable education entity.','STRING','EDUCATION','ACTIVE'),
('EDUCATION_DEGREE','Degree for one stable education entity.','STRING','EDUCATION','ACTIVE'),
('EDUCATION_FIELD_OF_STUDY','Field of study for one stable education entity.','STRING','EDUCATION','ACTIVE'),
('EDUCATION_DATE_RANGE','Dates for one stable education entity.','DATE_RANGE','EDUCATION','ACTIVE'),
('EDUCATION_GRADE','Grade stated for one education entity.','STRING','EDUCATION','ACTIVE'),
('EDUCATION_LOCATION','Location for one education entity.','STRING','EDUCATION','ACTIVE'),
('PROJECT_NAME','Name for one candidate project.','STRING','PROJECT','ACTIVE'),
('PROJECT_DESCRIPTION','Resume-supported description for one project.','RICH_TEXT','PROJECT','ACTIVE'),
('PROJECT_TECHNOLOGIES','Technologies stated for one project.','MULTI_ENUM','PROJECT','ACTIVE'),
('PROJECT_DATE_RANGE','Dates for one candidate project.','DATE_RANGE','PROJECT','ACTIVE'),
('PROJECT_URL','Link stated for one candidate project.','URL','PROJECT','ACTIVE'),
('CERTIFICATION_NAME','Name for one certification or award.','STRING','CERTIFICATION','ACTIVE'),
('CERTIFICATION_ISSUER','Issuer for one certification or award.','STRING','CERTIFICATION','ACTIVE'),
('CERTIFICATION_DATE','Date for one certification or award.','DATE','CERTIFICATION','ACTIVE'),
('CERTIFICATION_URL','Verification link for one certification.','URL','CERTIFICATION','ACTIVE'),
('CERTIFICATION_KIND','Whether the record is a certification or award.','ENUM','CERTIFICATION','ACTIVE'),
('CERTIFY_INFORMATION_ACCURATE','Application-specific accuracy certification.','BOOLEAN',NULL,'ACTIVE'),
('PRIVACY_ACKNOWLEDGEMENT','Application-specific privacy notice acknowledgement.','BOOLEAN',NULL,'ACTIVE'),
('BACKGROUND_CHECK_AUTHORIZATION','Application-specific background-check authorization.','BOOLEAN',NULL,'ACTIVE'),
('TERMS_ACKNOWLEDGEMENT','Application-specific terms acknowledgement.','BOOLEAN',NULL,'ACTIVE'),
('EEO_GENDER','Voluntary demographic gender disclosure.','ENUM',NULL,'ACTIVE'),
('EEO_RACE','Voluntary demographic race or ethnicity disclosure.','ENUM',NULL,'ACTIVE'),
('EEO_VETERAN','Voluntary veteran-status disclosure.','ENUM',NULL,'ACTIVE'),
('EEO_DISABILITY','Voluntary disability-status disclosure.','ENUM',NULL,'ACTIVE')
ON CONFLICT (canonical_key) DO NOTHING;

UPDATE canonical_answer_policies SET active=false WHERE active;
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','PERSONAL','STABLE_CANDIDATE_FACT',true FROM canonical_fields WHERE canonical_key='LEGAL_FIRST_NAME';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','PERSONAL','STABLE_CANDIDATE_FACT',true FROM canonical_fields WHERE canonical_key='LEGAL_MIDDLE_NAME';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','PERSONAL','STABLE_CANDIDATE_FACT',true FROM canonical_fields WHERE canonical_key='LEGAL_LAST_NAME';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_CANDIDATE_FACT',true FROM canonical_fields WHERE canonical_key='PREFERRED_FIRST_NAME';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_CANDIDATE_FACT',true FROM canonical_fields WHERE canonical_key='PREFERRED_LAST_NAME';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_CANDIDATE_FACT',true FROM canonical_fields WHERE canonical_key='FIRST_NAME';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_CANDIDATE_FACT',true FROM canonical_fields WHERE canonical_key='LAST_NAME';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_CANDIDATE_FACT',true FROM canonical_fields WHERE canonical_key='FULL_NAME';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','PERSONAL','STABLE_CANDIDATE_FACT',true FROM canonical_fields WHERE canonical_key='EMAIL';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','PERSONAL','STABLE_CANDIDATE_FACT',true FROM canonical_fields WHERE canonical_key='PHONE';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','PERSONAL','STABLE_CANDIDATE_FACT',true FROM canonical_fields WHERE canonical_key='CURRENT_ADDRESS';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_CANDIDATE_FACT',true FROM canonical_fields WHERE canonical_key='CURRENT_LOCATION';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_CANDIDATE_FACT',true FROM canonical_fields WHERE canonical_key='LINKEDIN_URL';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_CANDIDATE_FACT',true FROM canonical_fields WHERE canonical_key='GITHUB_URL';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_CANDIDATE_FACT',true FROM canonical_fields WHERE canonical_key='PORTFOLIO_URL';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'MUTABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],interval '180 days','MEDIUM','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','FRESH_MUTABLE_EMPLOYMENT_FACT',true FROM canonical_fields WHERE canonical_key='CURRENT_COMPANY';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'MUTABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],interval '180 days','MEDIUM','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','FRESH_MUTABLE_EMPLOYMENT_FACT',true FROM canonical_fields WHERE canonical_key='CURRENT_JOB_TITLE';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'MUTABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],interval '180 days','HIGH','AUTO','REVIEW_TO_SAVE',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','NEVER_INFER','PERSONAL','FRESH_COMPENSATION_FACT',true FROM canonical_fields WHERE canonical_key='CURRENT_CTC';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'MUTABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],interval '30 days','MEDIUM','AUTO','REVIEW_TO_SAVE',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','NEVER_INFER','NORMAL','FRESH_AVAILABILITY_FACT',true FROM canonical_fields WHERE canonical_key='NOTICE_PERIOD';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_CANDIDATE_FACT',true FROM canonical_fields WHERE canonical_key='TOTAL_EXPERIENCE';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_CANDIDATE_FACT',true FROM canonical_fields WHERE canonical_key='SKILLS';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_CANDIDATE_FACT',true FROM canonical_fields WHERE canonical_key='PERSONAL_SUMMARY';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL','JOB']::text[],ARRAY['JOB']::text[],ARRAY[]::text[],NULL,'MEDIUM','AUTO','REVIEW_TO_SAVE',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','NEVER_INFER','PERSONAL','CANDIDATE_SELECTED_DOCUMENT',true FROM canonical_fields WHERE canonical_key='RESUME';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'LEGAL_FACT','REVIEW',ARRAY['SEARCH']::text[],ARRAY['COUNTRY']::text[],ARRAY['COUNTRY']::text[],interval '180 days','HIGH','REVIEW','REVIEW_TO_SAVE',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'EXACT_SCOPE_TRIAL','NEVER_INFER','LEGAL','JURISDICTION_SCOPED_LEGAL_FACT',true FROM canonical_fields WHERE canonical_key='WORK_AUTHORIZATION';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'LEGAL_FACT','REVIEW',ARRAY['SEARCH']::text[],ARRAY['COUNTRY']::text[],ARRAY['COUNTRY']::text[],interval '180 days','HIGH','REVIEW','REVIEW_TO_SAVE',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'EXACT_SCOPE_TRIAL','NEVER_INFER','LEGAL','JURISDICTION_SCOPED_LEGAL_FACT',true FROM canonical_fields WHERE canonical_key='SPONSORSHIP_REQUIRED';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'LEGAL_FACT','REVIEW',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],interval '365 days','HIGH','REVIEW','REVIEW_TO_SAVE',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'EXACT_SCOPE_TRIAL','NEVER_INFER','LEGAL','CANDIDATE_CONFIRMED_LEGAL_FACT',true FROM canonical_fields WHERE canonical_key='AGE_OVER_18';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'LEGAL_FACT','REVIEW',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],interval '180 days','HIGH','REVIEW','REVIEW_TO_SAVE',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'EXACT_SCOPE_TRIAL','NEVER_INFER','LEGAL','CANDIDATE_CONFIRMED_LEGAL_FACT',true FROM canonical_fields WHERE canonical_key='GOVERNMENT_EMPLOYEE';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'LEGAL_FACT','REVIEW',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],interval '180 days','HIGH','REVIEW','REVIEW_TO_SAVE',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'EXACT_SCOPE_TRIAL','NEVER_INFER','LEGAL','CANDIDATE_CONFIRMED_LEGAL_FACT',true FROM canonical_fields WHERE canonical_key='NON_COMPETE';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'LEGAL_FACT','REVIEW',ARRAY['COMPANY']::text[],ARRAY['COMPANY']::text[],ARRAY['COMPANY']::text[],interval '180 days','HIGH','REVIEW','REVIEW_TO_SAVE',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'EXACT_SCOPE_TRIAL','NEVER_INFER','LEGAL','EXACT_COMPANY_SCOPE_REQUIRED',true FROM canonical_fields WHERE canonical_key='PREVIOUSLY_EMPLOYED_BY_COMPANY';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'LEGAL_FACT','REVIEW',ARRAY['COMPANY']::text[],ARRAY['COMPANY']::text[],ARRAY['COMPANY']::text[],interval '180 days','HIGH','REVIEW','REVIEW_TO_SAVE',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'EXACT_SCOPE_TRIAL','NEVER_INFER','LEGAL','EXACT_COMPANY_SCOPE_REQUIRED',true FROM canonical_fields WHERE canonical_key='RELATIVE_AT_COMPANY';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'PREFERENCE','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],interval '90 days','HIGH','AUTO','REVIEW_TO_SAVE',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'EXACT_SCOPE_TRIAL','NEVER_INFER','PERSONAL','CONTEXTUAL_PREFERENCE_WITH_GLOBAL_DEFAULT',true FROM canonical_fields WHERE canonical_key='EXPECTED_CTC';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'PREFERENCE','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'MEDIUM','AUTO','REVIEW_TO_SAVE',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'EXACT_SCOPE_TRIAL','NEVER_INFER','NORMAL','CONTEXTUAL_PREFERENCE_WITH_GLOBAL_DEFAULT',true FROM canonical_fields WHERE canonical_key='RELOCATION';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'PREFERENCE','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'MEDIUM','AUTO','REVIEW_TO_SAVE',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'EXACT_SCOPE_TRIAL','NEVER_INFER','NORMAL','CONTEXTUAL_PREFERENCE_WITH_GLOBAL_DEFAULT',true FROM canonical_fields WHERE canonical_key='PREFERRED_LOCATIONS';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'CONTEXTUAL','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],interval '30 days','MEDIUM','AUTO','REVIEW_TO_SAVE',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'EXACT_SCOPE_TRIAL','NEVER_INFER','NORMAL','VERIFIED_FACT_WITH_GLOBAL_DEFAULT',true FROM canonical_fields WHERE canonical_key='START_DATE';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'CONTEXTUAL','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'MEDIUM','AUTO','REVIEW_TO_SAVE',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'EXACT_SCOPE_TRIAL','NEVER_INFER','NORMAL','VERIFIED_FACT_WITH_GLOBAL_DEFAULT',true FROM canonical_fields WHERE canonical_key='WORK_MODE_REQUIREMENT';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'CONTEXTUAL','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'MEDIUM','AUTO','REVIEW_TO_SAVE',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'EXACT_SCOPE_TRIAL','NEVER_INFER','NORMAL','VERIFIED_FACT_WITH_GLOBAL_DEFAULT',true FROM canonical_fields WHERE canonical_key='LAST_WORKING_DAY';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'CONTEXTUAL','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'MEDIUM','AUTO','REVIEW_TO_SAVE',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'EXACT_SCOPE_TRIAL','NEVER_INFER','NORMAL','VERIFIED_FACT_WITH_GLOBAL_DEFAULT',true FROM canonical_fields WHERE canonical_key='AI_CODING_EXPERIENCE';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'CONTEXTUAL','AUTO',ARRAY['GLOBAL','SEARCH','COMPANY','JOB','APPLICATION']::text[],ARRAY['COUNTRY','ROLE_FAMILY','COMPANY','JOB','APPLICATION']::text[],ARRAY[]::text[],NULL,'MEDIUM','AUTO','REVIEW_TO_SAVE',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'EXACT_SCOPE_TRIAL','NEVER_INFER','NORMAL','VERIFIED_FACT_WITH_GLOBAL_DEFAULT',true FROM canonical_fields WHERE canonical_key='HEARING_SOURCE';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'CONTEXTUAL','DRAFT',ARRAY['APPLICATION']::text[],ARRAY['APPLICATION']::text[],ARRAY['APPLICATION']::text[],NULL,'MEDIUM','REVIEW','APPLICATION_ONLY',ARRAY[]::text[],'NEVER','GROUNDED_GENERATION','NORMAL','JOB_GROUNDED_WRITING',true FROM canonical_fields WHERE canonical_key='COVER_LETTER';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='EMPLOYMENT_COMPANY';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='EMPLOYMENT_TITLE';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='EMPLOYMENT_DATE_RANGE';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='EMPLOYMENT_LOCATION';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='EMPLOYMENT_DESCRIPTION';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='EMPLOYMENT_SKILLS';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='EDUCATION_INSTITUTION';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='EDUCATION_DEGREE';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='EDUCATION_FIELD_OF_STUDY';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='EDUCATION_DATE_RANGE';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='EDUCATION_GRADE';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='EDUCATION_LOCATION';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='PROJECT_NAME';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='PROJECT_DESCRIPTION';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='PROJECT_TECHNOLOGIES';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='PROJECT_DATE_RANGE';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='PROJECT_URL';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='CERTIFICATION_NAME';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='CERTIFICATION_ISSUER';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='CERTIFICATION_DATE';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='CERTIFICATION_URL';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'STABLE_FACT','AUTO',ARRAY['GLOBAL']::text[],ARRAY[]::text[],ARRAY[]::text[],NULL,'LOW','AUTO','AUTO_VERSION',ARRAY['VERIFIED_SUBMISSION','EXPLICIT_SAVE']::text[],'NEVER','DETERMINISTIC_ONLY','NORMAL','STABLE_ENTITY_FACT',true FROM canonical_fields WHERE canonical_key='CERTIFICATION_KIND';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'CONSENT','NEVER',ARRAY['APPLICATION']::text[],ARRAY['APPLICATION']::text[],ARRAY['APPLICATION']::text[],NULL,'HIGH','APPLICATION_GESTURE','APPLICATION_AUTHORIZATION',ARRAY[]::text[],'NEVER','NEVER_INFER','LEGAL','APPLICATION_DECLARATION_REQUIRES_GESTURE',true FROM canonical_fields WHERE canonical_key='CERTIFY_INFORMATION_ACCURATE';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'CONSENT','NEVER',ARRAY['APPLICATION']::text[],ARRAY['APPLICATION']::text[],ARRAY['APPLICATION']::text[],NULL,'HIGH','APPLICATION_GESTURE','APPLICATION_AUTHORIZATION',ARRAY[]::text[],'NEVER','NEVER_INFER','LEGAL','APPLICATION_DECLARATION_REQUIRES_GESTURE',true FROM canonical_fields WHERE canonical_key='PRIVACY_ACKNOWLEDGEMENT';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'CONSENT','NEVER',ARRAY['APPLICATION']::text[],ARRAY['APPLICATION']::text[],ARRAY['APPLICATION']::text[],NULL,'HIGH','APPLICATION_GESTURE','APPLICATION_AUTHORIZATION',ARRAY[]::text[],'NEVER','NEVER_INFER','LEGAL','APPLICATION_DECLARATION_REQUIRES_GESTURE',true FROM canonical_fields WHERE canonical_key='BACKGROUND_CHECK_AUTHORIZATION';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'CONSENT','NEVER',ARRAY['APPLICATION']::text[],ARRAY['APPLICATION']::text[],ARRAY['APPLICATION']::text[],NULL,'HIGH','APPLICATION_GESTURE','APPLICATION_AUTHORIZATION',ARRAY[]::text[],'NEVER','NEVER_INFER','LEGAL','APPLICATION_DECLARATION_REQUIRES_GESTURE',true FROM canonical_fields WHERE canonical_key='TERMS_ACKNOWLEDGEMENT';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'PROTECTED','NEVER',ARRAY['APPLICATION']::text[],ARRAY['APPLICATION']::text[],ARRAY[]::text[],NULL,'PROTECTED','FORBIDDEN','NEVER_LEARN',ARRAY[]::text[],'NEVER','NEVER_INFER','SENSITIVE','PROTECTED_OR_VOLUNTARY_VALUE',true FROM canonical_fields WHERE canonical_key='EEO_GENDER';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'PROTECTED','NEVER',ARRAY['APPLICATION']::text[],ARRAY['APPLICATION']::text[],ARRAY[]::text[],NULL,'PROTECTED','FORBIDDEN','NEVER_LEARN',ARRAY[]::text[],'NEVER','NEVER_INFER','SENSITIVE','PROTECTED_OR_VOLUNTARY_VALUE',true FROM canonical_fields WHERE canonical_key='EEO_RACE';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'PROTECTED','NEVER',ARRAY['APPLICATION']::text[],ARRAY['APPLICATION']::text[],ARRAY[]::text[],NULL,'PROTECTED','FORBIDDEN','NEVER_LEARN',ARRAY[]::text[],'NEVER','NEVER_INFER','SENSITIVE','PROTECTED_OR_VOLUNTARY_VALUE',true FROM canonical_fields WHERE canonical_key='EEO_VETERAN';
INSERT INTO canonical_answer_policies (id,canonical_id,policy_version,answer_class,reuse_mode,allowed_scope_types,scope_context_dimensions,required_context_dimensions,freshness_interval,risk_tier,autofill_mode,learning_mode,permanent_commit_points,review_reuse,derivation_policy,sensitivity,reason_code,active)
SELECT md5('job-hunter-v2:candidate-policy:3:' || canonical_key)::uuid,id,3,'PROTECTED','NEVER',ARRAY['APPLICATION']::text[],ARRAY['APPLICATION']::text[],ARRAY[]::text[],NULL,'PROTECTED','FORBIDDEN','NEVER_LEARN',ARRAY[]::text[],'NEVER','NEVER_INFER','SENSITIVE','PROTECTED_OR_VOLUNTARY_VALUE',true FROM canonical_fields WHERE canonical_key='EEO_DISABILITY';
