import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import type { Kysely } from "kysely";
import {sql} from "kysely";
import {CandidateTruthService,CandidateTruthResolver,HmacCandidateValueFingerprinter} from "@job-hunter-v2/candidate-truth";
import {AesGcmCandidatePayloadCipher} from "@job-hunter-v2/onboarding";
import {VerifiedLearningService} from "@job-hunter-v2/verified-learning";
import {FieldIntelligenceService,FieldSemanticResolver} from "@job-hunter-v2/field-intelligence";
import {RepresentationResolver} from "@job-hunter-v2/execution";
import {KyselyCandidateTruthRepository,KyselyVerifiedLearningRepository,KyselyLearningRecovery,type V2Database} from "@job-hunter-v2/database";
import type {ConfirmLearningNote,FieldEvidenceInput} from "@job-hunter-v2/contracts";

/** Synthetic fixed corpus. Production repositories/J/representation; no AI/network/DOM submission. */
export async function runLearningJourney(db:Kysely<V2Database>){
  const hmac=new HmacCandidateValueFingerprinter("synthetic-journey-fixture-secret-32-bytes",1),cipher=new AesGcmCandidatePayloadCipher(new Uint8Array(32).fill(6),1);
  const truthRepo=new KyselyCandidateTruthRepository(db),truth=new CandidateTruthService(truthRepo,hmac),recovery=new KyselyLearningRecovery(db,cipher,hmac),learning=new VerifiedLearningService(new KyselyVerifiedLearningRepository(db),hmac,cipher);
  const intelligence=new FieldIntelligenceService(new FieldSemanticResolver(),new CandidateTruthResolver(truthRepo)),representations=new RepresentationResolver();
  const candidate=async()=>{const owner={accountId:randomUUID(),candidateId:randomUUID()};await sql`INSERT INTO accounts(id,account_type,contributes_to_global_learning) VALUES(${owner.accountId},'TEST',false)`.execute(db);await truth.ensureCandidate(owner);return owner;};
  const active=await candidate(),baseline=await candidate();
  const fields=(application:number):FieldEvidenceInput[]=>{
    const labels=[['Current CTC','Current CTC (LPA)','Current salary monthly INR'],['Total years of experience','Total work experience','Total experience in months'],['Notice period','Notice period in days','What is your notice period?'],['When can you start?','Joining date','Available start date']];
    const pageId=randomUUID();return labels.map((variants,index)=>({evidenceVersion:1,fieldRuntimeId:`field:${index}:journey`,pageInstanceId:pageId,formInstanceId:'form:journey',sectionFingerprint:'section:journey',controlFingerprint:`control:${index}:journey`,controlType:index===3?'DATE':'TEXT',labelEvidence:[variants[(application-1)%3]!],contextEvidence:{section:null,previousLabel:null,nextLabel:null,semanticGroup:null,pageHeading:'Application',formHeading:null,nearbyDescription:null},locatorEvidence:{tagName:'input',type:index===3?'date':'text',name:null,id:null,autocomplete:null,ariaLabel:null,placeholder:null,role:null,accessibleDescription:null,occurrence:0},optionEvidence:{count:0,samples:[]},repeatableEvidence:{entityType:null,bindingKind:'NONE',instanceKey:null,candidateEntityId:null,ordinalHint:null,groupLabel:null},required:true,disabled:false,ownership:'UNKNOWN'}));
  };
  const marks:Array<{application:number;activeCorrect:number;baselineCorrect:number;attempted:number;wrong:number;abstained:number}>=[];
  let wrong=0,correct=0,baselineCorrect=0,total=0,aiCalls=0;
  for(let n=1;n<=20;n++){
    const runs=await Promise.all([active,baseline].map(owner=>learning.startRun({...owner,idempotencyKey:`journey:${n}`,request:{schemaVersion:1,requestId:randomUUID(),jobId:null,targetUrl:`https://synthetic.example.test/role-${n}/apply`,extensionVersion:'0.1.0',protocolVersion:1}})));
    const descriptors=fields(n),variant=(n-1)%3;
    // Gold values are independent literals; no expected output is generated by the converter.
    const expected=[['1200000','12','100000'][variant],['3 years 8 months','3 years 8 months','44'][variant],variant===1?'45':"45 days' notice",null];
    const pass=async(owner:typeof active,run:typeof runs[number])=>{
      const resolved=await intelligence.resolvePrivate({...owner,request:{schemaVersion:1,requestId:randomUUID(),applicationRunId:run.applicationRunId,pageContext:{host:'synthetic.example.test',ats:'GENERIC',pageHeading:'Application',jobId:null,applicationId:run.applicationId,countryCode:null,roleFamily:null,companyId:null},fields:descriptors}});
      aiCalls+=resolved.aiRequests;
      assert.equal(resolved.aiRequests,0,'this deterministic reuse benchmark must not invoke AI');
      const outputs=resolved.items.map((item,i)=>{if(item.semantic.state!=='RESOLVED_HIGH'||item.answerResolution?.status!=='RESOLVED')return null;try{const r=representations.resolve(item.answerResolution.normalizedValue,descriptors[i]!);return r.kind==='TEXT'?r.text:r.kind==='DATE'?r.isoDate:null;}catch{return null;}});
      return outputs;
    };
    const activeOutputs=await pass(active,runs[0]!),baselineOutputs=await pass(baseline,runs[1]!);
    let localCorrect=0,localWrong=0,attempted=0,baseCorrect=0;
    for(let i=0;i<descriptors.length;i++){
      const actual=activeOutputs[i];if(actual!==null){attempted++;if(actual===expected[i])localCorrect++;else localWrong++;}
      if(baselineOutputs[i]!==null&&baselineOutputs[i]===expected[i])baseCorrect++;
      // Date must never be manufactured from the notice duration saved earlier.
      if(i===3)assert.equal(actual,null,'no cross-application date or notice-to-date inference');
    }
    correct+=localCorrect;wrong+=localWrong;baselineCorrect+=baseCorrect;total+=4;
    if([1,5,10,20].includes(n))marks.push({application:n,activeCorrect:localCorrect,baselineCorrect:baseCorrect,attempted,wrong:localWrong,abstained:4-attempted});
    if(n===1){
      const inputs:ConfirmLearningNote[]=[{canonicalKey:'CURRENT_CTC',answer:'12',currency:'INR',scale:'LAKH',period:'YEAR',expectedCurrentVersionId:null,confirmedGlobalDefault:true},{canonicalKey:'TOTAL_EXPERIENCE',answer:'44',unit:'MONTHS',expectedCurrentVersionId:null,confirmedGlobalDefault:true},{canonicalKey:'NOTICE_PERIOD',answer:'45',unit:'DAYS',expectedCurrentVersionId:null,confirmedGlobalDefault:true},{canonicalKey:'START_DATE',answer:'2026-10-20',scope:'APPLICATION',expectedCurrentVersionId:null,confirmedGlobalDefault:false}];
      for(const input of inputs){const itemId=randomUUID();await recovery.capture(active,{schemaVersion:1,itemId,applicationId:runs[0]!.applicationId,applicationRunId:runs[0]!.applicationRunId,question:'Synthetic explicit confirmation',answer:input.answer,source:'EXPLICIT_SAVE'});await recovery.confirm(active,itemId,input);}
    }
  }
  return {evidence:'SYNTHETIC_PRODUCTION_REPOSITORY_SEMANTICS_REPRESENTATION_NOT_EMPLOYER_OR_DOM',applications:20,questions:total,correct,wrong,baselineCorrect,checkpoints:marks,aiCalls,scope:'Explicit candidate confirmations after application 1; frozen empty-profile control; 12 fixed wordings, not a sealed holdout or model training'};
}
