import { AdminPanel, AdminPanelHead, AdminShell } from "../../components/admin-shell";

export default function AdminApplications() {
  return <AdminShell active="/admin/applications" title="Application operations" subtitle="Monitor preparation, review and portal outcomes without reading private answer content.">
    <div className="admin-metrics compact"><article><p>Prepared · 24h</p><strong>1,842</strong><small>94.2% success</small></article><article><p>Waiting on user</p><strong>318</strong><small>17.3% of started</small></article><article><p>Confirmed submitted</p><strong>742</strong><small>40.3% of started</small></article><article><p>Median prepare time</p><strong>3m 18s</strong><small>p95 · 8m 42s</small></article></div>
    <div className="admin-grid-main"><AdminPanel><AdminPanelHead eyebrow="Last 24 hours" title="State transitions" /><div className="transition-flow"><div><strong>1,954</strong><small>Started</small></div><span>→</span><div><strong>1,842</strong><small>Prepared</small></div><span>→</span><div><strong>1,524</strong><small>User reviewed</small></div><span>→</span><div><strong>742</strong><small>Confirmed</small></div></div><div className="transition-notes"><span><i className="health-light good" /> Prepare success within target</span><span><i className="health-light warn" /> Review-to-submit below baseline</span></div></AdminPanel><AdminPanel><AdminPanelHead eyebrow="Failure composition" title="What stopped runs" /><div className="reason-bars"><div><span>Portal selector drift <b>42%</b></span><i><b style={{width:'42%'}} /></i></div><div><span>Missing user evidence <b>31%</b></span><i><b style={{width:'31%'}} /></i></div><div><span>Portal session expired <b>18%</b></span><i><b style={{width:'18%'}} /></i></div><div><span>Attachment failure <b>9%</b></span><i><b style={{width:'9%'}} /></i></div></div></AdminPanel></div>
    <AdminPanel><AdminPanelHead eyebrow="Sampled events · content redacted" title="Recent application runs" action={<button>Download logs</button>} /><div className="admin-data-table application-admin-table"><div className="admin-data-row table-head"><span>Run ID</span><span>Portal</span><span>Plan</span><span>State</span><span>Duration</span><span>Reason</span><span>Time</span></div>{[['app_8F2A','Greenhouse','Free','Prepared','2m 42s','—','12:41'],['app_8F29','Workday','Pro','Failed','7m 18s','Attachment retry exhausted','12:39'],['app_8F28','Naukri','Free','Paused','1m 03s','User evidence required','12:37'],['app_8F27','LinkedIn','Pro','Reviewed','3m 51s','—','12:34'],['app_8F26','Greenhouse','Free','Confirmed','2m 19s','—','12:30']].map(row => <div className="admin-data-row" key={row[0]}>{row.map((cell,index) => <span key={cell}>{index === 3 ? <b className={`state-tag ${cell.toLowerCase()}`}>{cell}</b> : cell}</span>)}</div>)}</div></AdminPanel>
  </AdminShell>;
}
